---
version: '3'

services:
  http-echo:
    image: hashicorp/http-echo
    ports:
      - "5678:5678"
    command: "-text=foo"
  watchtower:
    image: containrrr/watchtower:latest
    environment:
      - "WATCHTOWER_POLL_INTERVAL=30"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock