services:
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    environment:
      - "WATCHTOWER_POLL_INTERVAL=30"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json
