hosts:
  martin:
    stacks: ["echo", "test"]
    configs: ["martin-echo"]
    prestart-scripts: ["martin-prestart.sh"]
    crons:
      - schedule: "* * * * *"
        service: "cron-echo"
    environment:
      - "SOMETHING=something_baz"
      - "SOMETHING_ELSE=something_foo_bar"